name: Montréal
gtfs_url: https://www.stm.info/sites/default/files/gtfs/gtfs_stm.zip
gtfs_rt:
  trip_updates: https://api.stm.info/pub/od/gtfs-rt/ic/v2/tripUpdates
  alerts: https://api.stm.info/pub/od/i3/v2/messages/etatservice
bbox:
  south: 45.228
  west: -74.266
  north: 45.988
  east: -73.062
polygon: config/polygons/grand_montreal.geojson
